// packages/gridsome/src/pages/Index.vue
<template>
  <form method="POST" :action="formActionUrl">
    <textarea name="message" placeholder="Message" />
    <button type="submit">Send</button>
  </form>
</template>

<script>
export default {
  metaInfo: {
    title: "Contact",
  },
  data() {
    return {
      formActionUrl: "https://submit-form.com/your-form-id",
    };
  },
};
</script>

// packages/gatsby/src/pages/index.jsx
import React from "react";

const FORMSPARK_ACTION_URL = "https://submit-form.com/your-form-id";

export default function HomePage() {
  return (
    <form method="POST" action={FORMSPARK_ACTION_URL}>
      <textarea name="message" placeholder="Message" />
      <button type="submit">Send</button>
    </form>
  );
}
